### ISSUE TITLE
page uses a lot of external resources

### ISSUE THREAD

**Issue by abma** [spring-rts-ru/springrts-ru-website#1]
see sourcecode of http://springrts.ru/

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js
https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js

they should be hosted locally
- privacy
- load time should decrease (fewer dns / tcp connections needed)
- no external dependency (can't break because external server is broken)

cdn's are often disliked by adblockers, too.

**Comment by jamerlan** [comment]
nah, its OK. All these files are usually cached already by browsers so it will be faster then using local copies

**Comment by jamerlan** [comment]
http://www.sitepoint.com/7-reasons-to-use-a-cdn/

**Comment by jamerlan** [comment]
also here: https://developer.yahoo.com/performance/rules.html
Use a Content Delivery Network

**Comment by abma** [comment]
http://www.sitepoint.com/7-reasons-not-to-use-a-cdn/

**Comment by abma** [comment]
in short, its VERY bad to use a cdn / external files.

**Comment by jamerlan** [comment]
for now its ok. I did it intentionally
